name: Build LaTeX
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
jobs:       
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: .
          root_file: "src/main.tex"
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -jobname=paper"
      - name: Push PDF file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.pdf'
          commit_message: Added PDF product
          commit_user_name: Build LaTeX
          commit_user_email: test@example.org # Needed to display commit_user_name
